/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

/* Define to 1 if you have `alloca', as a function or macro. */
#define HAVE_ALLOCA 1

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the `getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the <math.h> header file. */
#define HAVE_MATH_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have a working `mmap' system call. */
/* #define HAVE_MMAP 1 */

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the `setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <termio.h> header file. */
#define HAVE_TERMIO_H 1

/* Define to 1 if you have the `tmpfile' function. */
#define HAVE_TMPFILE 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Binary age of MiniGUI */
#define MINIGUI_BINARY_AGE 0

/* Interface age of MiniGUI */
#define MINIGUI_INTERFACE_AGE 0

/* Major version of MiniGUI */
#define MINIGUI_MAJOR_VERSION 1

/* Micro version of MiniGUI */
#define MINIGUI_MICRO_VERSION 2

/* Minor version of MiniGUI */
#define MINIGUI_MINOR_VERSION 6

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at run-time.
        STACK_DIRECTION > 0 => grows toward higher addresses
        STACK_DIRECTION < 0 => grows toward lower addresses
        STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
#undef TM_IN_SYS_TIME

/* Define if support Arabic charset */
/* #undef _ARABIC_SUPPORT */

/* Define if include input engine for ARM3000 */
/* #undef _ARM3000_IAL */

/* Define if include the automatic IAL engine */
/*   #undef _AUTO_IAL */

/* Define if support BIG5 charset */
/* #define _BIG5_SUPPORT 1 */

/* Define if include clipboard support */
   #define _CLIPBOARD_SUPPORT 1

/* Define if use coordinate transformation */
/* #undef _COOR_TRANS */

   #define __MINIGUI_LIB__ 1

/* Define if include RESOURCES in CORE */
   #define _INCORE_RES 1

/* Define if include BUTTON control */
   #define _CTRL_BUTTON 1

/* Define if include COMBOBOX control */
   #define _CTRL_COMBOBOX 1

/* Define if include LISTBOX control */
   #define _CTRL_LISTBOX 1

/* Define if include MENUBUTTON control */
   #define _CTRL_MENUBUTTON 1

/* Define if include NEWTOOLBAR control */
   #define _CTRL_NEWTOOLBAR 1

/* Define if include PROGRESSBAR control */
   #define _CTRL_PROGRESSBAR 1

/* Define if include PROPSHEET control */
   #define _CTRL_PROPSHEET 1

/* Define if include SCROLLVIEW control */
   #define _CTRL_SCROLLVIEW 1

/* Define if include SIMEDIT control */
   #define _CTRL_SIMEDIT 1

/* Define if include SLEDIT control */
   #define _CTRL_SLEDIT 1 

/* Define if include STATIC control */
   #define _CTRL_STATIC 1

/* Define if include TEXTEDIT control */
   #define _CTRL_TEXTEDIT 1

/* Define if include TOOLBAR control */
   #define _CTRL_TOOLBAR 1

/* Define if include TRACKBAR control */
   #define _CTRL_TRACKBAR 1

/* Define if include cursor support */
   #define _CURSOR_SUPPORT 1

/* Define if support Cyrillic charset */
/* #undef _CYRILLIC_SUPPORT */

/* Define if build with debugging messages */
/* #undef _DEBUG */

/* Define if mouse button can do double click */
/* #define _DOUBLE_CLICK 1 */

/* Define if include the dummy IAL engine */
   #define _DUMMY_IAL 1 

/* Define if include input engine for EMBEST ARM2410 */
/* #undef _EMBEST2410_IAL */

/* Define if include input engine for xScale EVMV 1.0 */
/* #undef _EVMV10_IAL */

/* Define if include 16BPP FB subdriver */
/* #define _FBLIN16_SUPPORT 1 */

/* Define if include 1BPP FB subdriver (MSB is left) */
/* #undef _FBLIN1L_SUPPORT */

/* Define if include 1BPP FB subdriver (MSB is right) */
/* #undef _FBLIN1R_SUPPORT */

/* Define if include 24BPP FB subdriver */
/* #undef _FBLIN24_SUPPORT */

/* Define if include 2BPP FB subdriver (MSB is left) */
/* #undef _FBLIN2L_SUPPORT */

/* Define if include 2BPP FB subdriver (MSB is right) */
/* #undef _FBLIN2R_SUPPORT */

/* Define if include 32BPP FB subdriver */
/* #undef _FBLIN32_SUPPORT */

/* Define if include 4BPP FB subdriver (MSB is left) */
/* #undef _FBLIN4L_SUPPORT */

/* Define if include 4BPP FB subdriver (MSB is right) */
/* #undef _FBLIN4R_SUPPORT */

/* Define if include 8BPP FB subdriver */
   #define _FBLIN8_SUPPORT 1

/* Define if include input engine for FFT7202 */
/* #undef _FFT7202_IAL */

/* Define if include fixed math routines */
#define _FIXED_MATH 1

/* Define if window style is flat */
/* #define _FLAT_WINDOW_STYLE 1 */

/* Define if include input engine for FXRM9200 */
/* #undef _FXRM9200_IAL */

/* Define if support GB2312 charset */
/* #define _GB_SUPPORT 1 */

/* Define if support GIF bmp file format */
/* #define _GIF_FILE_SUPPORT 1 */

/* Define if include GPM mouse subdriver */
/* #define _GPM_SUPPORT 1 */

/* Define if is gray screen */
//#define _GRAY_SCREEN 1

/* Define if support Greek charset */
/* #undef _GREEK_SUPPORT */

/* Define if have math library */
#define _HAVE_MATH_LIB 1

/* Define if your Linux have text mode */
/* #define _HAVE_TEXT_MODE 1 */

/* Define if support Hebrew charset */
/* #undef _HEBREW_SUPPORT */

/* Define if include IAL engine for HHARM2410R3 touch screen */
/* #undef _HH2410R3_IAL */

/* Define if include GB2312 IME */
/* #define _IME_GB2312 1 */

/* Define if include IMPS2 mouse subdriver */
/* #define _IMPS2_SUPPORT 1 */

/* Define if include input engine for iPAQ */
/* #undef _IPAQ_IAL */

/* Define if support JPEG bmp file format */
/* #define _JPG_FILE_SUPPORT 1 */

/* Define if use the German keyboard layout */
/* #undef _KBD_LAYOUT_DE */

/* Define if use the German-Latin1 keyboard layout */
/* #undef _KBD_LAYOUT_DELATIN1 */

/* Define if use the Spanish keyboard layout */
/* #undef _KBD_LAYOUT_ES */

/* Define if use the Spanish CP850 keyboard layout */
/* #undef _KBD_LAYOUT_ESCP850 */

/* Define if use the French keyboard layout */
/* #undef _KBD_LAYOUT_FR */

/* Define if use the French PC keyboard layout */
/* #undef _KBD_LAYOUT_FRPC */

/* Define if use the Italian keyboard layout */
/* #undef _KBD_LAYOUT_IT */

/* Define if include input engine for L7200 */
/* #undef _L7200_IAL */

/* Define if support Latin 10 charset */
/* #undef _LATIN10_SUPPORT */

/* Define if support Latin 2 charset */
/* #undef _LATIN2_SUPPORT */

/* Define if support Latin 3 charset */
/* #undef _LATIN3_SUPPORT */

/* Define if support Latin 4 charset */
/* #undef _LATIN4_SUPPORT */

/* Define if support Latin 5 charset */
/* #undef _LATIN5_SUPPORT */

/* Define if support Latin 6 charset */
/* #undef _LATIN6_SUPPORT */

/* Define if support Latin 7 charset */
/* #undef _LATIN7_SUPPORT */

/* Define if support Latin 8 charset */
/* #undef _LATIN8_SUPPORT */

/* Define if support Latin 9 charset */
/* #define _LATIN9_SUPPORT 1 */

/* Define if build lite version of MiniGUI */
/* #undef _LITE_VERSION */

/* Define if include IAL engine for uClinux touch screen palm/mc68ez328 */
/* #undef _MC68X328_IAL */

/* Define if include About MiniGUI Dialog Box */
/* #define _MISC_ABOUTDLG 1 */

/* Define if include code for mouse calibration */
/* #define _MISC_MOUSECALIBRATE 1 */

/* Define if include code for screenshots */
/* #define _MISC_SAVESCREEN 1 */

/* Define if we can move window by mouse */
   #define _MOVE_WINDOW_BY_MOUSE 1

/* Define if include MS3 mouse subdriver */
/* #define _MS3_SUPPORT 1 */

/* Define if include messages' string names */
/* #undef _MSG_STRING */

/* Define if include MS mouse subdriver */
/* #define _MS_SUPPORT 1 */

/* Define if include native graphics engine */
   #define _NATIVE_GAL_ENGINE 1

/* Define if support native graphics engine on FBCON */
   #define _NATIVE_GAL_FBCON 1

/* Define if support native graphics engine on QVFB */
/* #define _NATIVE_GAL_QVFB 1 */

/* Define if include native input engine */
/* #define _NATIVE_IAL_ENGINE 1 */

/* Define if window style is PC 3D */
   #define _PC3D_WINDOW_STYLE 1

/* Define if window style is phone */
/* #undef _PHONE_WINDOW_STYLE */

/* Define if support PNG bmp file format */
/* #define _PNG_FILE_SUPPORT 1 */

/* Define if include PS2 mouse subdriver */
/* #define _PS2_SUPPORT 1 */

/* Define if include input engine for PX255B */
/* #undef _PX255B_IAL */

/* Define if include the QVFB IAL engine */
/* #define _QVFB_IAL 1 */

/* Define if support raw bitmap fonts */
/* #define _RBF_SUPPORT 1 */

/* Define to 0 if use clockwise rotation of screen, otherwise to 1 */
/* #undef _ROT_DIR_CW */

/* Define if include SaveBitmap function */
//   #define _SAVE_BITMAP 1

/* Define if include IAL engine for SMDK2410 touch screen */
/* #undef _SMDK2410_IAL */

/* Define if build stand-alone version of MiniGUI-Lite */
/* #undef _STAND_ALONE */

/* Define if support Thai charset */
/* #undef _THAI_SUPPORT */

/* Define if include input engine for THOR */
/* #undef _THOR_IAL */

/* Define if the unit of timer is 10ms */
#define _TIMER_UNIT_10MS 1

/* Define if it is tiny screen */
//   #define _TINY_SCREEN 1

/* Define if trace message dispatching of MiniGUI */
/* #undef _TRACE_MSG */

/* Define if use minigui_entry function in MiniGUI */
/* #undef _USE_MINIGUIENTRY */

/* Define if support var bitmap fonts */
#define _VBF_SUPPORT 1
#define _INCOREFONT_COURIER 1

/* Define if include input engine for NEC VR4181 */
/* #undef _VR4181_IAL */

/* Define if compile for Linux */
/* #define __LINUX__ 1 */

/* Define for unknown target */
#define __TARGET_UNKNOWN__ 1

/* Define if compile for uClinux */
/* #undef __uClinux__ */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define as `__inline' if that's what the C compiler calls it, or to nothing
   if it is not supported. */
/* #undef inline */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */
